version: "3.8"
services:
  php:
    environment:
    - XDEBUG_MODE=coverage
    container_name: damas-php
    image: damas-php
    build:
      context: "php"
      args:
        UID: ${UID}
        GID: ${GID}
    networks:
    - docker
    volumes:
    - ..:/app
    - ~/.config/composer/auth.json:/home/app/.composer/auth.json
    - ~/.ssh/:/home/app/.ssh:ro
networks:
  docker:
    name: docker
